import * as smooth from "@pixi/graphics-smooth";
import * as particles from "@pixi/particle-emitter";
import {
    AccessibilityManager,
    ALPHA_MODES,
    AlphaFilter,
    Application,
    BaseTexture,
    BatchGeometry,
    BatchRenderer,
    BatchShaderGenerator,
    BLEND_MODES,
    BlurFilter,
    Bounds,
    Circle,
    CLEAR_MODES,
    Color,
    ColorSource,
    Container,
    DisplayObject,
    Ellipse,
    EventBoundary,
    Extract,
    FederatedEvent,
    FederatedPointerEvent,
    FederatedWheelEvent,
    Filter,
    FilterState,
    FilterSystem,
    FORMATS,
    Geometry,
    Graphics,
    Graphics as LegacyGraphics,
    IBaseTextureOptions,
    IBatchableElement,
    IDestroyOptions,
    IPointData,
    ITextStyle,
    Matrix,
    Mesh,
    MIPMAP_MODES,
    MSAA_QUALITY,
    ObservablePoint,
    ParticleContainer,
    ParticleRenderer,
    Point,
    Polygon,
    Prepare,
    Program,
    Rectangle,
    Renderer,
    RenderTexture,
    RoundedRectangle,
    SCALE_MODES,
    settings,
    Shader,
    SHAPES,
    Sprite,
    Spritesheet,
    Text,
    TextStyle,
    Texture,
    TextureUvs,
    TilingSpriteRenderer,
    Transform,
    TYPES,
    UniformGroup,
    utils,
    ViewableBuffer,
} from "pixi.js";
import "./board.d.ts";
import "./core/index.d.ts";
import "./fog-manager.d.ts";
import "./groups/index.d.ts";
import "./helpers/index.d.ts";
import "./layers/index.d.ts";
import "./perception/index.d.ts";
import "./placeable.d.ts";
import "./placeables/index.d.ts";
import "./sources/index.d.ts";
import "./special-effect/index.d.ts";
import "./webgl/index.d.ts";

declare global {
    module PIXI {
        export {
            AccessibilityManager,
            AlphaFilter,
            Application,
            ALPHA_MODES,
            BLEND_MODES,
            BaseTexture,
            BatchGeometry,
            BatchRenderer,
            BatchShaderGenerator,
            BlurFilter,
            Bounds,
            CLEAR_MODES,
            Circle,
            Color,
            ColorSource,
            Container,
            DisplayObject,
            Ellipse,
            EventBoundary,
            Extract,
            FederatedEvent,
            FederatedPointerEvent,
            FederatedWheelEvent,
            Filter,
            FilterState,
            FilterSystem,
            FORMATS,
            Geometry,
            Graphics,
            IBaseTextureOptions,
            IBatchableElement,
            IDestroyOptions,
            IPointData,
            ITextStyle,
            LegacyGraphics,
            Matrix,
            Mesh,
            MIPMAP_MODES,
            MSAA_QUALITY,
            ParticleContainer,
            ParticleRenderer,
            Point,
            Polygon,
            Prepare,
            Program,
            ObservablePoint,
            Rectangle,
            RenderTexture,
            Renderer,
            RoundedRectangle,
            SCALE_MODES,
            SHAPES,
            Shader,
            Sprite,
            Spritesheet,
            TYPES,
            Text,
            TextStyle,
            Texture,
            TextureAlphaData,
            TextureUvs,
            TilingSpriteRenderer,
            Transform,
            UniformGroup,
            ViewableBuffer,
            particles,
            settings,
            smooth,
            utils,
        };
    }
}
