ignoredBuiltDependencies:
  - '@parcel/watcher'
  - classic-level
  - unrs-resolver

onlyBuiltDependencies:
    - esbuild

minimumReleaseAge: 4320
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080
