import { ImmunityData } from "@actor/data/iwr";
import { ImmunityType } from "@actor/types";
import { IWRRuleElement } from "./base";
/** @category RuleElement */
declare class ImmunityRuleElement extends IWRRuleElement {
    protected dictionary: {
        acid: string;
        adamantine: string;
        air: string;
        "area-damage": string;
        auditory: string;
        bleed: string;
        blinded: string;
        bludgeoning: string;
        chaotic: string;
        clumsy: string;
        cold: string;
        "cold-iron": string;
        confused: string;
        conjuration: string;
        controlled: string;
        "critical-hits": string;
        curse: string;
        darkwood: string;
        dazzled: string;
        deafened: string;
        "death-effects": string;
        disease: string;
        doomed: string;
        drained: string;
        earth: string;
        electricity: string;
        emotion: string;
        enchantment: string;
        energy: string;
        enfeebled: string;
        evil: string;
        evocation: string;
        fascinated: string;
        fatigued: string;
        "fear-effects": string;
        fire: string;
        "flat-footed": string;
        fleeing: string;
        force: string;
        frightened: string;
        good: string;
        grabbed: string;
        healing: string;
        illusion: string;
        immobilized: string;
        inhaled: string;
        lawful: string;
        light: string;
        magic: string;
        mental: string;
        "misfortune-effects": string;
        mithral: string;
        necromancy: string;
        negative: string;
        "non-magical": string;
        "nonlethal-attacks": string;
        "object-immunities": string;
        olfactory: string;
        orichalcum: string;
        paralyzed: string;
        petrified: string;
        physical: string;
        piercing: string;
        poison: string;
        polymorph: string;
        positive: string;
        possession: string;
        precision: string;
        prone: string;
        restrained: string;
        "salt-water": string;
        scrying: string;
        sickened: string;
        silver: string;
        slashing: string;
        sleep: string;
        slowed: string;
        sonic: string;
        "spell-deflection": string;
        stunned: string;
        stupefied: string;
        "swarm-attacks": string;
        "swarm-mind": string;
        transmutation: string;
        trip: string;
        "unarmed-attacks": string;
        unconscious: string;
        visual: string;
        water: string;
    };
    get property(): ImmunityData[];
    getIWR(): ImmunityData[];
}
interface ImmunityRuleElement extends IWRRuleElement {
    type: ImmunityType[];
    exceptions: ImmunityType[];
}
export { ImmunityRuleElement };
