/// <reference types="jquery" />
/// <reference types="jquery" />
/// <reference types="tooltipster" />
import { CoinsPF2e, PhysicalItemSheetPF2e } from "@item/physical";
import { OneToFour } from "@module/data";
import { SheetOptions } from "@module/sheet/helpers";
import { WeaponPropertyRuneSlot } from "./data";
import { type WeaponPF2e } from "./document";
interface PropertyRuneSheetSlot extends WeaponPropertyRuneSlot {
    name?: string;
    number?: OneToFour;
    label?: string;
}
export declare class WeaponSheetPF2e extends PhysicalItemSheetPF2e<WeaponPF2e> {
    getData(options?: Partial<DocumentSheetOptions>): Promise<{
        hasDetails: boolean;
        hasSidebar: boolean;
        preciousMaterials: import("../physical/sheet").PreparedMaterials;
        weaponPotencyRunes: {
            1: string;
            2: string;
            3: string;
            4: string;
        };
        weaponStrikingRunes: {
            striking: string;
            greaterStriking: string;
            majorStriking: string;
        };
        weaponPropertyRunes: {
            [k: string]: string;
        };
        otherTags: SheetOptions;
        adjustedDiceHint: string | null;
        adjustedLevelHint: string | null;
        adjustedPriceHint: string | null;
        abpEnabled: boolean;
        baseDice: number;
        baseLevel: number;
        rarity: "unique" | "common" | "uncommon" | "rare";
        basePrice: CoinsPF2e;
        categories: {
            simple: string;
            martial: string;
            advanced: string;
            unarmed: string;
        };
        groups: Record<"dart" | "knife" | "axe" | "brawling" | "club" | "flail" | "hammer" | "pick" | "polearm" | "shield" | "spear" | "sword" | "bomb" | "bow" | "firearm" | "sling", string>;
        baseTypes: Record<"dart" | "club" | "flail" | "pick" | "spear" | "sling" | "adze" | "air-repeater" | "aklys" | "alchemical-bomb" | "alchemical-crossbow" | "aldori-dueling-sword" | "arquebus" | "asp-coil" | "atlatl" | "axe-musket" | "barricade-buster" | "bastard-sword" | "battle-axe" | "battle-lute" | "battle-saddle" | "bec-de-corbin" | "big-boom-gun" | "black-powder-knuckle-dusters" | "bladed-diabolo" | "bladed-gauntlet" | "bladed-hoop" | "bladed-scarf" | "blowgun" | "blowgun-darts" | "blunderbuss" | "bo-staff" | "boarding-axe" | "boarding-pike" | "bola" | "boomerang" | "bow-staff" | "breaching-pike" | "broadspear" | "butchering-axe" | "butterfly-sword" | "buugeng" | "cane-pistol" | "chain-sword" | "chakram" | "chakri" | "clan-dagger" | "clan-pistol" | "claw" | "claw-blade" | "coat-pistol" | "combat-grapnel" | "combat-lure" | "composite-longbow" | "composite-shortbow" | "corset-knife" | "crescent-cross" | "crossbow" | "dagger" | "dagger-pistol" | "daikyu" | "dancers-spear" | "dandpatta" | "dogslicer" | "donchak" | "double-barreled-musket" | "double-barreled-pistol" | "dragon-mouth-pistol" | "dueling-pistol" | "dueling-spear" | "dwarven-dorn-dergar" | "dwarven-scattergun" | "dwarven-war-axe" | "earthbreaker" | "elven-branched-spear" | "elven-curve-blade" | "explosive-dogslicer" | "exquisite-sword-cane" | "exquisite-sword-cane-sheath" | "falcata" | "falchion" | "fangwire" | "fauchard" | "feng-huo-lun" | "fighting-fan" | "fighting-stick" | "filchers-fork" | "fire-lance" | "fire-poi" | "fist" | "flingflenser" | "flintlock-musket" | "flintlock-pistol" | "flying-talon" | "flyssa" | "forked-bipod" | "frying-pan" | "gada" | "gaff" | "gakgung" | "gauntlet" | "gauntlet-bow" | "gill-hook" | "glaive" | "gnome-amalgam-musket" | "gnome-flickmace" | "gnome-hooked-hammer" | "greataxe" | "greatclub" | "greatpick" | "greatsword" | "griffon-cane" | "guisarme" | "gun-sword" | "halberd" | "halfling-sling-staff" | "hammer-gun" | "hand-adze" | "hand-cannon" | "hand-crossbow" | "harmona-gun" | "harpoon" | "hatchet" | "heavy-crossbow" | "hongali-hornbow" | "hook-sword" | "horsechopper" | "injection-spear" | "javelin" | "jaws" | "jezail" | "jiu-huan-dao" | "juggling-club" | "kalis" | "kama" | "karambit" | "katana" | "katar" | "khakkhara" | "khopesh" | "knuckle-duster" | "kris" | "kukri" | "kusarigama" | "lance" | "lancer" | "leiomano" | "light-hammer" | "light-mace" | "light-pick" | "lion-scythe" | "long-air-repeater" | "long-hammer" | "longbow" | "longspear" | "longsword" | "mace" | "mace-multipistol" | "machete" | "main-gauche" | "mambele" | "maul" | "meteor-hammer" | "mikazuki" | "mithral-tree" | "monkeys-fist" | "morningstar" | "naginata" | "nightstick" | "nine-ring-sword" | "nodachi" | "nunchaku" | "ogre-hook" | "orc-knuckle-dagger" | "orc-necksplitter" | "panabas" | "pepperbox" | "phalanx-piercer" | "piercing-wind" | "piranha-kiss" | "poi" | "polytool" | "probing-cane" | "ranseur" | "rapier" | "rapier-pistol" | "reinforced-wheels" | "repeating-crossbow" | "repeating-hand-crossbow" | "repeating-heavy-crossbow" | "rhoka-sword" | "rope-dart" | "rotary-bow" | "rungu" | "sai" | "sansetsukon" | "sap" | "sawtooth-saber" | "scimitar" | "scizore" | "scorpion-whip" | "scourge" | "scythe" | "shauth-lash" | "shears" | "shield-bash" | "shield-boss" | "shield-bow" | "shield-pistol" | "shield-spikes" | "shobhad-longrifle" | "shortbow" | "shortsword" | "shuriken" | "sickle" | "sickle-saber" | "slide-pistol" | "sling-bullets" | "spiked-chain" | "spiked-gauntlet" | "spiral-rapier" | "spoon-gun" | "spraysling" | "staff" | "starknife" | "stiletto-pen" | "sukgung" | "sun-sling" | "switchscythe" | "sword-cane" | "talwar" | "tamchal-chakram" | "taw-launcher" | "tekko-kagi" | "temple-sword" | "tengu-gale-blade" | "thorn-whip" | "three-peaked-tree" | "three-section-naginata" | "throwing-knife" | "thunder-sling" | "thundermace" | "tonfa" | "tri-bladed-katar" | "tricky-pick" | "trident" | "triggerbrand" | "urumi" | "visap" | "wakizashi" | "war-flail" | "war-lance" | "war-razor" | "warhammer" | "wheel-blades" | "wheel-spikes" | "whip" | "whip-claw" | "whip-staff" | "wish-blade" | "wish-knife" | "wooden-taws" | "wrecker" | "wrist-launcher" | "zulfikar", string>;
        itemBonuses: {
            "-2": string;
            0: string;
            1: string;
            2: string;
            3: string;
        };
        damageDieFaces: {
            [k: string]: string;
        };
        damageDie: {
            d4: string;
            d6: string;
            d8: string;
            d10: string;
            d12: string;
        };
        damageDice: {
            0: string;
            1: string;
            2: string;
            3: string;
            4: string;
        };
        conditionTypes: Record<"hidden" | "blinded" | "broken" | "clumsy" | "confused" | "controlled" | "dazzled" | "deafened" | "doomed" | "drained" | "enfeebled" | "fascinated" | "fatigued" | "flat-footed" | "fleeing" | "frightened" | "grabbed" | "immobilized" | "paralyzed" | "petrified" | "prone" | "restrained" | "sickened" | "slowed" | "stunned" | "stupefied" | "unconscious" | "concealed" | "dying" | "encumbered" | "friendly" | "helpful" | "hostile" | "indifferent" | "invisible" | "observed" | "persistent-damage" | "quickened" | "undetected" | "unfriendly" | "unnoticed" | "wounded", string>;
        damageTypes: Record<"force" | "chaotic" | "evil" | "good" | "lawful" | "bludgeoning" | "piercing" | "slashing" | "bleed" | "acid" | "cold" | "electricity" | "fire" | "sonic" | "positive" | "negative" | "mental" | "poison" | "untyped", string>;
        weaponRanges: {
            [x: number]: string;
        };
        mandatoryMelee: boolean;
        mandatoryRanged: boolean;
        weaponReload: Record<import("./types").WeaponReloadTime, string>;
        weaponMAP: {
            1: string;
            2: string;
            3: string;
            4: string;
            5: string;
        };
        isBomb: boolean;
        isComboWeapon: boolean;
        meleeGroups: Record<"dart" | "knife" | "axe" | "brawling" | "club" | "flail" | "hammer" | "pick" | "polearm" | "shield" | "spear" | "sword", string>;
        meleeUsage: import("./data").ComboWeaponMeleeUsage;
        meleeUsageTraits: SheetOptions;
        isPhysical: true;
        priceAdjustment: "lower" | "higher" | null;
        actionTypes: {
            action: string;
            reaction: string;
            free: string;
            passive: string;
        };
        actionsNumber: {
            1: string;
            2: string;
            3: string;
        };
        bulkTypes: {
            L: string;
            1: string;
            2: string;
            3: string;
            4: string;
            5: string;
            6: string;
            7: string;
            8: string;
            9: string;
            10: string;
            11: string;
            12: string;
            13: string;
            14: string;
            15: string;
            16: string;
            17: string;
            18: string;
            19: string;
            20: string;
            21: string;
            22: string;
            23: string;
            24: string;
            25: string;
            26: string;
            27: string;
            28: string;
            29: string;
            30: string;
            31: string;
            32: string;
            33: string;
            34: string;
            35: string;
            36: string;
            37: string;
            38: string;
            39: string;
            40: string;
            41: string;
            42: string;
            43: string;
            44: string;
            45: string;
            46: string;
            47: string;
            48: string;
            49: string;
            50: string;
        };
        frequencies: {
            PT1M: string;
            PT10M: string;
            PT1H: string;
            PT24H: string;
            day: string;
            P1W: string;
        };
        sizes: Record<"tiny" | "sm" | "med" | "lg" | "huge" | "grg", string>;
        stackGroups: {
            arrows: string;
            blowgunDarts: string;
            bolts: string;
            coins: string;
            gems: string;
            rounds5: string;
            rounds10: string;
            rations: string;
            sacks: string;
            slingBullets: string;
            sprayPellets: string;
            woodenTaws: string;
        };
        usage: {
            "affixed-to-a-creature": string;
            "affixed-to-a-magical-staff": string;
            "affixed-to-a-ranged-weapon": string;
            "affixed-to-a-shield": string;
            "affixed-to-a-thrown-weapon": string;
            "affixed-to-a-two-handed-firearm-or-crossbow": string;
            "affixed-to-an-innovation": string;
            "affixed-to-an-object-or-structure": string;
            "affixed-to-armor": string;
            "affixed-to-medium-heavy-armor": string;
            "affixed-to-armor-or-a-weapon": string;
            "affixed-to-armor-or-travelers-clothing": string;
            "affixed-to-crossbow-or-firearm": string;
            "affixed-to-firearm": string;
            "affixed-to-firearm-with-a-reload-of-1": string;
            "affixed-to-firearm-with-the-kickback-trait": string;
            "affixed-to-ground-in-10-foot-radius": string;
            "affixed-to-ground-in-20-foot-radius": string;
            "affixed-to-harness": string;
            "affixed-to-headgear": string;
            "affixed-to-instrument": string;
            "affixed-to-load-bearing-wall-or-pillar": string;
            "affixed-to-object-structure-or-creature": string;
            "affixed-to-the-ground": string;
            "affixed-to-unarmored-defense-item": string;
            "affixed-to-weapon": string;
            "applied-to-a-basket-bag-or-other-container": string;
            "applied-to-a-weapon": string;
            "applied-to-a-wind-powered-vehicle": string;
            "applied-to-a-non-injection-melee-weapon-piercing-damage": string;
            "applied-to-any-item-of-light-or-negligible-bulk": string;
            "applied-to-any-visible-article-of-clothing": string;
            "applied-to-armor": string;
            "applied-to-armor-or-unarmored-defense-clothing": string;
            "applied-to-belt-cape-cloak-or-scarf": string;
            "applied-to-boots-cape-cloak-or-umbrella": string;
            "applied-to-buckler-shield": string;
            "applied-to-dueling-cape-or-shield": string;
            "applied-to-footwear": string;
            "applied-to-medium-heavy-armor": string;
            "applied-to-shield": string;
            "attached-to-a-thrown-weapon": string;
            "attached-to-crossbow-or-firearm": string;
            "attached-to-crossbow-or-firearm-firing-mechanism": string;
            "attached-to-crossbow-or-firearm-scope": string;
            "attached-to-firearm": string;
            "attached-to-firearm-scope": string;
            bonded: string;
            "each-rune-applied-to-a-separate-item-that-has-pockets": string;
            "etched-onto-a-weapon": string;
            "etched-onto-armor": string;
            "etched-onto-heavy-armor": string;
            "etched-onto-light-armor": string;
            "etched-onto-metal-armor": string;
            "etched-onto-clan-dagger": string;
            "etched-onto-lm-nonmetal-armor": string;
            "etched-onto-med-heavy-armor": string;
            "etched-onto-melee-weapon": string;
            "etched-onto-slashing-melee-weapon": string;
            "etched-onto-piercing-or-slashing-melee-weapon": string;
            "etched-onto-weapon-wo-anarchic-rune": string;
            "etched-onto-weapon-wo-axiomatic-rune": string;
            "etched-onto-weapon-wo-unholy-rune": string;
            "etched-onto-weapon-wo-holy-rune": string;
            "etched-onto-melee-weapon-monk": string;
            "etched-onto-thrown-weapon": string;
            "held-in-one-hand": string;
            "held-in-one-hand-or-free-standing": string;
            "held-in-two-hands": string;
            other: string;
            "sewn-into-clothing": string;
            "tattooed-on-the-body": string;
            touched: string;
            worn: string;
            wornamulet: string;
            wornanklets: string;
            wornarmbands: string;
            wornbackpack: string;
            wornbarding: string;
            wornbelt: string;
            wornbeltpouch: string;
            wornboots: string;
            wornbracelet: string;
            wornbracers: string;
            worncap: string;
            worncape: string;
            worncirclet: string;
            worncloak: string;
            wornclothing: string;
            worncollar: string;
            worncrown: string;
            wornepaulet: string;
            worneyeglasses: string;
            worneyepiece: string;
            wornfootwear: string;
            worngarment: string;
            worngloves: string;
            wornheadwear: string;
            wornhorseshoes: string;
            wornmask: string;
            wornnecklace: string;
            wornonbelt: string;
            wornoronehand: string;
            wornring: string;
            wornsaddle: string;
            wornsandles: string;
            wornshoes: string;
            wornwrist: string;
            "worn-and-attached-to-two-weapons": string;
            "worn-under-armor": string;
        };
        bulkDisabled: boolean;
        activations: {
            action: import("../physical/data").ItemActivation;
            id: string;
            base: string;
            description: string;
            traits: SheetOptions;
        }[];
        itemType: string | null;
        showTraits: boolean;
        sidebarTitle: string;
        sidebarTemplate?: (() => string) | undefined;
        detailsTemplate?: (() => string) | undefined;
        item: WeaponPF2e<import("../../actor/base").ActorPF2e<import("../../scene/token-document/document").TokenDocumentPF2e<import("../../scene/document").ScenePF2e | null> | null> | null>;
        data: import("./data").WeaponSystemData;
        enrichedContent: Record<string, string>;
        user: {
            isGM: boolean;
        };
        enabledRulesUI: boolean;
        ruleEditing: boolean;
        rarities: {
            common: string;
            uncommon: string;
            rare: string;
            unique: string;
        };
        traits: SheetOptions | null;
        traitTagifyData: import("@module/sheet/helpers").TraitTagifyEntry[] | null;
        rules: {
            labels: {
                label: string;
                recognized: boolean;
            }[];
            selection: {
                selected: string | null;
                types: Record<string, string>;
            };
            elements: {
                template: string;
                index: number;
                rule: import("../../rules/rule-element/data").RuleElementSource;
            }[];
        };
        proficiencies: readonly ["PF2E.ProficiencyLevel0", "PF2E.ProficiencyLevel1", "PF2E.ProficiencyLevel2", "PF2E.ProficiencyLevel3", "PF2E.ProficiencyLevel4"];
        cssClass: string;
        editable: boolean;
        document: WeaponPF2e<import("../../actor/base").ActorPF2e<import("../../scene/token-document/document").TokenDocumentPF2e<import("../../scene/document").ScenePF2e | null> | null> | null>;
        limited: boolean;
        options: FormApplicationOptions;
        owner: boolean;
        title: string;
        propertyRuneSlots?: PropertyRuneSheetSlot[] | undefined;
    }>;
    activateListeners($html: JQuery): void;
    protected _updateObject(event: Event, formData: Record<string, unknown>): Promise<void>;
}
export {};
