export const AON_CREATURE_TYPES: string[] = [
    "aberration",
    "animal",
    "astral",
    "beast",
    "celestial",
    "construct",
    "dragon",
    "dream",
    "elemental",
    "ethereal",
    "fey",
    "fiend",
    "fungus",
    "giant",
    "humanoid",
    "monitor",
    "ooze",
    "plant",
    "shade",
    "time",
    "undead",
    "vitality",
    "void",
];

export const ELITE_WEAK: string[] = ["elite", "weak"];
